// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leorolland/sortir.in/pkg/application (interfaces: EventRepository)

// Package applicationmocks is a generated GoMock package.
package applicationmocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	application "github.com/leorolland/sortir.in/pkg/application"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// ByBoundsAndDateRange mocks base method.
func (m *MockEventRepository) ByBoundsAndDateRange(arg0 application.Bounds, arg1, arg2 time.Time) ([]application.Pin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByBoundsAndDateRange", arg0, arg1, arg2)
	ret0, _ := ret[0].([]application.Pin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByBoundsAndDateRange indicates an expected call of ByBoundsAndDateRange.
func (mr *MockEventRepositoryMockRecorder) ByBoundsAndDateRange(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByBoundsAndDateRange", reflect.TypeOf((*MockEventRepository)(nil).ByBoundsAndDateRange), arg0, arg1, arg2)
}
